version: '3.8'

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php/php.dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'dbpass'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
    networks:
      - laravel

  npm:
    image: node:14
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  phpunit:
    build:
      context: .
      dockerfile: php/php.dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - laravel

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: php/php.dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - laravel